### PR TITLE
Ayush Kumar Baranwal 2020CH10082

### PR DESCRIPTION
**Pull request by Ayush-Baranwal-X**

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Hi, you have put semi-colons after entryNum and name, replace them by commas instead.

**Comment by Ayush-Baranwal-X** [comment]
> Hi, you have put semi-colons after entryNum and name, replace them by commas instead.

Sir i removed it. Is it ok now? Do i have to create a new pull request or not?

**Comment by JapneetSingh5** [comment]
No, this pull request got updated automatically.
Please fill in the form, I'll merge your PR after that.

**Comment by Ayush-Baranwal-X** [comment]
> No, this pull request got updated automatically.
> Please fill in the form, I'll merge your PR after that.

Done sir

**Pull request merged**
