### PR TITLE
Anish Roy 2020ME10911

### PR DESCRIPTION
**Pull request by anishroy1802**
I have added my entry in my pull request

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Hi, your code is giving an error! 
Do not delete the contacts field completely! Remove only the inner blocks in {..}, leave the empty array as it is

**Comment by JapneetSingh5** [comment]
Hi, your code is giving an error, put a comma i.e ..}, {.. between your block {..} and the one before you and also a comma after it ends, before the ]

**Comment by anishroy1802** [comment]
I have made the respective changes to my entry. Hope it is fine now

**Comment by anishroy1802** [comment]
Made the changes, as mentioned.
Pl check and mention anything else I need to change as well

Regards,
Anish Roy
2020ME10911

**Comment by JapneetSingh5** [comment]
Hi, your pull request is perfect 👍 , just fill in this form https://forms.gle/sci4X9pq4SoLTazm9 so that we have a log of your participation in this assignment! Once done, I'll merge your pull request into the repository.

**Comment by anishroy1802** [comment]
> Hi, your pull request is perfect 👍 , just fill in this form https://forms.gle/sci4X9pq4SoLTazm9 so that we have a log of your participation in this assignment! Once done, I'll merge your pull request into the repository.



> Hi, your pull request is perfect 👍 , just fill in this form https://forms.gle/sci4X9pq4SoLTazm9 so that we have a log of your participation in this assignment! Once done, I'll merge your pull request into the repository.

Sir I have filled in the form

**Pull request merged**
