### PR TITLE
Harsh Vardhan Singh Patel 2020BB10020

### PR DESCRIPTION
**Pull request by hvsp2704**

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Hi, your entryNum format is incorrect. It should be the last 4 digits only minus the padded zeroes in the front i.e just 20 in your case.

**Comment by JapneetSingh5** [comment]
Make this change, commit it and it will be reflected in this PR only, no need to make another pull request

**Comment by hvsp2704** [comment]
Sir, I made the req changes and have pushed it.Do I have to do anything else? Or its fine now?On 27 Jan 2021 18:59, Japneet Singh <notifications@github.com> wrote:
Make this change, commit it and it will be reflected in this PR only, no need to make another pull request

**Comment by JapneetSingh5** [comment]
Looks like you forgot to PUSH the changes after committing them!

**Comment by hvsp2704** [comment]
Sorry for this much trouble due to my carelessness. Now I have pushed 
it.

**Comment by JapneetSingh5** [comment]
No problem at all!

**Pull request merged**
