### PR TITLE
VISHWAS KALANI 2020CS10411

### PR DESCRIPTION
**Pull request by vishwaskalani**

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Add ]; after your block ends i.e 
{
...
},
];

**Comment by vishwaskalani** [comment]
Sir should I send u my link again on Google form after adding the bracket

**Comment by vishwaskalani** [comment]
Sir will my pull request not be accepted Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [devclub-iitd/GitAssignment2021] VISHWAS KALANI 2020CS10411 (#100)From: Japneet Singh To: devclub-iitd/GitAssignment2021 CC: vishwaskalani ,Author 
Add ]; after your block ends i.e
{
...
},
];

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/devclub-iitd/GitAssignment2021/pull/100#issuecomment-768481518",
"url": "https://github.com/devclub-iitd/GitAssignment2021/pull/100#issuecomment-768481518",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JapneetSingh5** [comment]
Perfect! Well done

**Comment by vishwaskalani** [comment]
Thanks a lot.

**Pull request merged**
