### PR TITLE
Raushan kumar 2020CS1190

### PR DESCRIPTION
**Pull request by raushan-kumar-2020**

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Your entry has not been added. Please check and reach out if you have any doubts!

**Comment by raushan-kumar-2020** [comment]
modified

**Comment by JapneetSingh5** [comment]
Whatever you did made no difference in the PR, do you need help?

**Comment by raushan-kumar-2020** [comment]
added

**Comment by raushan-kumar-2020** [comment]
added entry

**Comment by arpit-saxena** [comment]
@raushan-kumar-2020 Do one thing, delete your forked repository and fork it again. Then follow instructions in the assignment. 
Here are a few pointers to help you:
- You have to edit the file `src/Freshers.js`
- Then you need to create a PR from your **master** branch. This PR is from some other branch.

Please feel free to ask for further clarifications.

PS: To delete, go to (your fork)[https://github.com/raushan-kumar-2020/GitAssignment2021], then click Settings at top right. When you scroll down, there will be an option to delete

**Comment by raushan-kumar-2020** [comment]
Duplicate of #

**Pull request closed without merging**
